apiVersion: gateway.networking.k8s.io/v1alpha2
kind: BackendTLSPolicy
metadata:
  name: ai-data-capture-backend-tls
  namespace: ai-data-capture
  labels:
    app: ai-data-capture-api
    environment: production
spec:
  # Target the backend service
  targetRef:
    group: ""
    kind: Service
    name: ai-data-capture-api-service
    sectionName: http
  
  # TLS configuration for backend communication
  tls:
    # Use system CA bundle for backend verification
    caCertRefs:
    - name: backend-ca-cert
      kind: Secret
    
    # Hostname for backend TLS verification
    hostname: ai-data-capture-api-service.ai-data-capture.svc.cluster.local
---
# Backend CA certificate secret (if using mTLS to backend)
# Uncomment and configure if your backend requires TLS
# apiVersion: v1
# kind: Secret
# metadata:
#   name: backend-ca-cert
#   namespace: ai-data-capture
#   labels:
#     app: ai-data-capture-api
#     environment: production
# type: Opaque
# data:
#   ca.crt: ""  # Base64 encoded CA certificate for backend verification
