# ClusterIssuer for Let's Encrypt production certificates
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  labels:
    app: ai-data-capture-api
    environment: production
spec:
  acme:
    # Let's Encrypt production server
    server: https://acme-v02.api.letsencrypt.org/directory
    
    # Email for Let's Encrypt notifications (CHANGE THIS TO YOUR EMAIL)
    email: demolasobaki@gmail.com
    
    # Private key secret for ACME account
    privateKeySecretRef:
      name: letsencrypt-prod-private-key
    
    # HTTP01 challenge solver for domain validation via Gateway API
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
          - name: ai-data-capture-gateway
            namespace: ai-data-capture
            kind: Gateway
---
# ClusterIssuer for Let's Encrypt staging (for testing)
#apiVersion: cert-manager.io/v1
#kind: ClusterIssuer
#metadata:
#  name: letsencrypt-staging
#  labels:
#    app: ai-data-capture-api
#    environment: staging
#spec:
#  acme:
#    # Let's Encrypt staging server (for testing)
#    server: https://acme-staging-v02.api.letsencrypt.org/directory
#
#    # Email for Let's Encrypt notifications
#    email: your-email@example.com
#
#    # Private key secret for ACME account
#    privateKeySecretRef:
#      name: letsencrypt-staging-private-key
#
#    # HTTP01 challenge solver for domain validation
#    solvers:
#    - http01:
#        gatewayHTTPRoute:
#          parentRefs:
#          - name: ai-data-capture-gateway
#            namespace: ai-data-capture
#            kind: Gateway
