# TLS Certificate for apidatacapture.store domain
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apidatacapture-store-tls
  namespace: ai-data-capture
  labels:
    app: ai-data-capture-api
    environment: production
spec:
  # Secret where the certificate will be stored
  secretName: apidatacapture-store-tls-secret
  
  # Certificate issuer (use staging for testing, prod for production)
  issuerRef:
    name: letsencrypt-prod  # Change to letsencrypt-staging for testing
    kind: ClusterIssuer
    group: cert-manager.io
  
  # Domain names for the certificate
  dnsNames:
  - apidatacapture.store
  - www.apidatacapture.store
  
  # Certificate configuration
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days before expiry
  
  # Private key configuration
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  
  # Certificate usage
  usages:
  - digital signature
  - key encipherment
  
  # Subject configuration
  subject:
    organizationalUnits:
    - "AI Data Capture Portal"
    organizations:
    - "AI Data Capture"
    countries:
    - "US"
