apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ai-data-capture-api-pdb
  namespace: ai-data-capture
  labels:
    app: ai-data-capture-api
    environment: production
spec:
  minAvailable: 2  # Ensure at least 2 pods are always available during disruptions
  selector:
    matchLabels:
      app: ai-data-capture-api
