# Helm values for cert-manager
# Production-ready configuration for cert-manager

# Install CRDs automatically
installCRDs: true

# Global settings
global:
  # Leader election namespace
  leaderElection:
    namespace: cert-manager
  
  # Log level (1-5, higher = more verbose)
  logLevel: 2
  
  # Pod security context
  podSecurityPolicy:
    enabled: false
    useAppArmor: false

# cert-manager controller settings
replicaCount: 1

image:
  repository: quay.io/jetstack/cert-manager-controller
  tag: v1.13.0
  pullPolicy: IfNotPresent

# Resource limits and requests
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 32Mi

# Node selector and tolerations
nodeSelector: {}
tolerations: []
affinity: {}

# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# Service account
serviceAccount:
  create: true
  annotations: {}

# Webhook settings
webhook:
  replicaCount: 1
  timeoutSeconds: 30
  
  image:
    repository: quay.io/jetstack/cert-manager-webhook
    tag: v1.13.0
    pullPolicy: IfNotPresent
  
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 32Mi
  
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000

# CA Injector settings
cainjector:
  enabled: true
  replicaCount: 1
  
  image:
    repository: quay.io/jetstack/cert-manager-cainjector
    tag: v1.13.0
    pullPolicy: IfNotPresent
  
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 32Mi
  
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000

# Prometheus monitoring
prometheus:
  enabled: true
  servicemonitor:
    enabled: true
    prometheusInstance: default
    targetPort: 9402
    path: /metrics
    interval: 60s
    scrapeTimeout: 30s
    labels: {}

# Startup API check
startupapicheck:
  enabled: true
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  
  timeout: 1m
  backoffLimit: 4
  
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 32Mi

# Extra arguments for cert-manager
extraArgs:
  - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53
  - --dns01-recursive-nameservers-only
  - --enable-certificate-owner-ref=true

# Extra environment variables
extraEnv: []

# Pod disruption budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Network policy
networkPolicy:
  enabled: false
