"""added field to counsellee table

Revision ID: 4da336cbd8ca
Revises: ed6eb9a9c7ac
Create Date: 2024-12-21 02:06:22.941638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4da336cbd8ca'
down_revision: Union[str, None] = 'ed6eb9a9c7ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('counsellee', sa.Column('attended_to', sa.Boolean(), server_default='FALSE', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('counsellee', 'attended_to')
    # ### end Alembic commands ###
