"""update database schema

Revision ID: 515b7ca1898f
Revises: b2c3d4e5f6g7
Create Date: 2025-12-21 01:21:52.435265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '515b7ca1898f'
down_revision: Union[str, None] = 'b2c3d4e5f6g7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Don't create role enum - it already exists from users table migration
    # Just reference the existing enum type
    op.create_table('counsellors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('has_certification', sa.Boolean(), nullable=False),
    sa.Column('denomination', sa.String(length=100), nullable=True),
    sa.Column('will_attend_ymr', sa.Boolean(), nullable=False),
    sa.Column('is_available_for_training', sa.Boolean(), nullable=False),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    sa.Column('certificates', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', 'super-admin', name='role', create_type=False), server_default='user', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('counsellors')
    # ### end Alembic commands ###
