"""update database schema

Revision ID: 515b7ca1898f
Revises: b2c3d4e5f6g7
Create Date: 2025-12-21 01:21:52.435265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '515b7ca1898f'
down_revision: Union[str, None] = 'b2c3d4e5f6g7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use raw SQL to create table with existing role enum to avoid duplicate enum error
    op.execute("""
        CREATE TABLE counsellors (
            id SERIAL PRIMARY KEY,
            name VARCHAR NOT NULL,
            email VARCHAR NOT NULL UNIQUE,
            password VARCHAR,
            phone_number VARCHAR,
            gender VARCHAR,
            country VARCHAR,
            state VARCHAR,
            date_of_birth VARCHAR,
            address VARCHAR,
            years_of_experience INTEGER,
            has_certification BOOLEAN NOT NULL,
            denomination VARCHAR(100),
            will_attend_ymr BOOLEAN NOT NULL,
            is_available_for_training BOOLEAN NOT NULL,
            profile_image_url VARCHAR,
            certificates VARCHAR,
            is_active BOOLEAN NOT NULL DEFAULT FALSE,
            role role NOT NULL DEFAULT 'user',
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
        )
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('counsellors')
    # ### end Alembic commands ###
