"""add country and state fields to counsellors table

Revision ID: 58b7e28553a6
Revises: d286036a8739
Create Date: 2024-12-21 10:33:15.629854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58b7e28553a6'
down_revision: Union[str, None] = 'd286036a8739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('counsellors', sa.Column('country', sa.String(), nullable=True))
    op.add_column('counsellors', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('counsellors', 'state')
    op.drop_column('counsellors', 'country')
    # ### end Alembic commands ###
