"""add online field to converts table

Revision ID: acbe25120325
Revises: 947d0fe50e93
Create Date: 2024-12-20 22:56:20.479623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acbe25120325'
down_revision: Union[str, None] = '947d0fe50e93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('counsellee', sa.Column('online', sa.Boolean(), server_default='FALSE', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('counsellee', 'online')
    # ### end Alembic commands ###
