"""add counsellee table

Revision ID: db018d07cf7f
Revises: f6062f208db4
Create Date: 2024-12-19 12:20:48.777919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db018d07cf7f'
down_revision: Union[str, None] = 'f6062f208db4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counsellee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.String(), nullable=True),
    sa.Column('relationship_status', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('nearest_bus_stop', sa.String(), nullable=True),
    sa.Column('is_student', sa.Boolean(), server_default='FALSE', nullable=True),
    sa.Column('age_group', sa.String(), nullable=True),
    sa.Column('school', sa.String(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('denomination', sa.String(), nullable=True),
    sa.Column('counselling_reason', sa.String(), nullable=True),
    sa.Column('counsellor_name', sa.String(), nullable=True),
    sa.Column('counsellor_comments', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('counsellee')
    # ### end Alembic commands ###
