"""Add header_image to templates

Revision ID: ebb27f7222d5
Revises: 9408053e27e4
Create Date: 2025-11-22 23:52:37.031413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebb27f7222d5'
down_revision: Union[str, None] = '9408053e27e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_templates', sa.Column('header_image', sa.String(), nullable=True))
    op.add_column('notification_templates', sa.Column('created_by', sa.Integer(), nullable=True))
    op.alter_column('notification_templates', 'body',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('notification_templates', 'html_body',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('notification_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_notification_templates_id'), 'notification_templates', ['id'], unique=False)
    op.create_foreign_key(None, 'notification_templates', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification_templates', type_='foreignkey')
    op.drop_index(op.f('ix_notification_templates_id'), table_name='notification_templates')
    op.alter_column('notification_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('notification_templates', 'html_body',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('notification_templates', 'body',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('notification_templates', 'created_by')
    op.drop_column('notification_templates', 'header_image')
    # ### end Alembic commands ###
