"""remove online field from counsellee table and add to converts able

Revision ID: ed6eb9a9c7ac
Revises: acbe25120325
Create Date: 2024-12-20 22:59:41.311552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed6eb9a9c7ac'
down_revision: Union[str, None] = 'acbe25120325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('converts', sa.Column('online', sa.Boolean(), server_default='FALSE', nullable=True))
    op.drop_column('counsellee', 'online')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('counsellee', sa.Column('online', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_column('converts', 'online')
    # ### end Alembic commands ###
