name: Production Deploy on Changes

on: 
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
jobs:
  build:
    environment:
      name: testing
    env:
      DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}}
      DATABASE_PORT: ${{secrets.DATABASE_PORT}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
      AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
      AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY}}
      AWS_REGION: ${{secrets.AWS_REGION}}
      S3_BUCKET: ${{secrets.S3_BUCKET}}
      OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Install python version 3.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: Start the application
        run: |
          uvicorn app.main:app --host 127.0.0.1 --port 8000 &
          sleep 5
          curl -f http://127.0.0.1:8000/ || exit 1
        env:
          ENVIRONMENT: production
          DEBUG: "False"

      - name: Stop the application
        run: kill $(lsof -t -i:8000)
  
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: testing
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Set up SSH access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 13.61.24.195 >> ~/.ssh/known_hosts
  
      - name: Deploy to EC2 server
        uses: appleboy/ssh-action@master
        with:
          host: "${{secrets.SERVER_HOST_IP}}"
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /app/
            source venv/bin/activate
            cd /src/
            git pull origin main
            pip install -r requirements.txt
            sudo systemctl restart api